name: Glide
version: '${project.version}'
main: net.hackedlecterns.glide.Glide
api-version: '1.16'
commands:
  boost1:
  boost2:
  boost3x:
  boost3z:
  boost3nx:
  boost3nz:
  testCommand:
  start:
  addboost:
  addcheckpoint:
  addthermal:
  createcourse:
  editcourse:
  finishcourse:
  pos1:
  pos2:
  removecourse:
  setfinish:
  setstart:

permissions:
  glide.start:
    - default: true