name: Glide
version: '${project.version}'
main: net.hackedlecterns.glide.Main
api-version: '1.16'
commands:
  glide:
    description: The main command for glide
    usage: /glide [subcommand]
    aliases:
      - gl

permissions:
  glide.start:
    description: permission to execute /glide join
    default: true
